### ISSUE TITLE
README.md hangs browser

### ISSUE THREAD

**Issue by welchr** [R-js/libRmath.js#10]
On both the github page for the repository, and the npm page, the browser will hang for quite a while trying to render the extensive README.md - eventually I will get the "kill or wait for this page" dialog (maybe my machine is just really slow.) 

One solution could be to separate the docs into a separate .md file, and point to it from the README.md instead.

**Comment by jacobbogers** [comment]
Good idea,
I was planning to split the readme up into its sections, (since more things will be added in the future).
I am planning a new release next month based on all the feedbacks I get, 

thanks for your beedback.
