### ISSUE TITLE
allowing lambda to be a vector in rpois(n,lambda).

### ISSUE THREAD

**Issue by stephenjewson** [R-js/libRmath.js#104]
Hello
Thanks for making libRmath available. It's very useful for me. 
I'm new to github, so pls forgive me if I'm typing the wrong thing in the wrong place.
With the command rpois, in R it's possible for the lambda to be a vector. 
So, for instance, I can generate two random numbers from distributions with different lambdas using the command rpois(2,c(1,1000)).
Would it be possible to implement it like that in libRmath.js?
I'm thinking it might be faster (my code requires 100,000 different lambdas, each with a different value).
thanks
s

**Comment by jacobbogers** [comment]
Hi @stephenjewson , I am glad the library is useful to you
firstly

the [R recycling rule](https://cran.r-project.org/doc/manuals/r-release/R-intro.html#The-recycling-rule) is build into the R language, but you  you can mimic it in `lib-r-math` with the function [`multiplex`](https://github.com/R-js/libRmath.js#multiplex)  wrapper function, 

Let me explain with example
```R
rpois(2, c(1, 1000))
```
Equivalent in javascript with library

```javascript

const libR = require('lib-r-math.js');
const { multiplex, c } = libR.R;
const { Poisson } = libR;

const { dpois, ppois, qpois, rpois } = Poisson();

rpoisCycle = multiplex(rpois); // rpoisCycle follows R recycling rule 

rpoisCycle(1, c(1, 1000)); // first argument set to "1" always for "`r`xyz" variates of distribution `xyz`
// gives back 2 numbers for lambda = 1 and lambda = 1000
```

Let me know if this works for you

**Comment by stephenjewson** [comment]
Hi Jacob,
Thankyou for the quick reply. That looks very clear. I will need a moment to study it. 
s

**Comment by jacobbogers** [comment]
Hi @stephenjewson 
Forgot to mention
instead of `c` , you could just use an array 

```javascript
rpoisCycle = multiplex(rpois); 

let arr = [2,9,8 ...]; // big array of data, loaded from somewhere

rpoisCycle(1, arr);
```

Cheers

**Comment by jacobbogers** [comment]
I am closing this issue, Let me know if the solution was helpfull

**Comment by stephenjewson** [comment]
Sorry, got distracted with other things.
The solution worked. Very nice.  I learnt something about R too.
thanks
s
