### ISSUE TITLE
Enable Travis CI for PRs of (outside) contributors

### ISSUE THREAD

**Issue by DanielRuf** [R-js/libRmath.js#15]
Currently it seems Travis CI is not enabled for all PRs, see https://github.com/R-js/libRmath.js/pull/14

**Comment by jacobbogers** [comment]
Thanks for your contribution DanielRuf, Feel free to create more issues wich you think are helpfull for the project

**Comment by mmaechler** [comment]
Sw@2@aAWa

Jacob Bogersqday <notifications@github.com> schrieb am Mo., 12.11.2018,
16:47:wwa
>
> Closed #15.
>
> -- AWO
> a are receiving this because you 1qa subscribed to this thread.
> Reply to this email directly An AA@2@1@2@AQQ@Q@@ wAaa@@@2@ae# view it on
GitHub:
> https://github.com/R-js/libRmath.js/issues/15#event-1960651435
>         [[alternative HTML version deleted]]
>
>

**Comment by mmaechler** [comment]
YA£aae

**Comment by mmaechler** [comment]
aAAA

Jacob Bogers <notifications@github.com> schrieb am Mo., 12.11.2018, 16:47:

**Comment by jacobbogers** [comment]
We are now on gitter https://gitter.im/r-js-org
