### ISSUE TITLE
require in Observable

### ISSUE THREAD

**Issue by neocarto** [R-js/libRmath.js#158]
require("lib-r-math.js") dosen't work within [Observable](https://observablehq.com/)

**Comment by jacobbogers** [comment]
Hi @neocarto 

I am not familiar with ObservableHQ, but I found this link

https://observablehq.com/@observablehq/module-require-debugger

After entering `lib-r-math.js` in the input field it showed me this screenshot (below) on how to use it

I guess "Observable"s run in a browser in that case you can access all functions from `window.libR` prefix or `libR` prefix

Note: _I am not sure how Observable execute javascript (sandboxed?),_

In any case the new version of `lib-r-math.js` (2.0) will use the standardized [JS module system](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules).

![image](https://user-images.githubusercontent.com/896018/175506869-7dccf23c-c276-4f41-b088-061a703d08c7.png)

**Comment by neocarto** [comment]
Unfortunately, the require does not work in observable for the moment. Anyway, I can't wait to try lib-r-math.js (2.0). Do you know when this version will be available?

**Comment by jacobbogers** [comment]
@neocarto, sorry for getting back at you so late, it will be available on 01.nov.2022

**Comment by neocarto** [comment]
2023 ?

**Comment by jacobbogers** [comment]
Corrected))

**Comment by jacobbogers** [comment]
Hi @neocarto , I got it working on observablehq.com (see screenshot below made from the website using the lib)

It is version 2.0.0 release candidate rc1, there are a number of breaking changes, but you can browse the exported functions in observable and infer their usage,

I still have to re-write the document (README.md) , some distributions have a wasm backend (`useHyperGeomBackend` and `useSignRankBackend`)

Let me know if this is working for you

Cheers,   

![image](https://user-images.githubusercontent.com/896018/206519485-689fd3e1-474a-4ae0-88f4-64752bb17b17.png)

**Comment by jacobbogers** [comment]
I released the first beta of version 2.0.0, lots of things changed, the README.md is a lot smaller and more succinct, a lot of unit tests, etc

version 2.0.0 is now the main branch in the repo, let me know if you find any typos and what not, 

https://github.com/R-js/libRmath.js

**Comment by jacobbogers** [comment]
@neocarto,

Version 2.0.0 officially released, note the "breaking changes" and wasm backends https://www.npmjs.com/package/lib-r-math.js?activeTab=readme
