### ISSUE TITLE
can't use rmultinom with n = 1

### ISSUE THREAD

**Issue by bluelovers** [R-js/libRmath.js#16]
can't use libRmath.Multinomial rmultinom with n = 1, only when n > 1, it will not throw error

```ts
  const result = sequence(n).map(() => _rmultinom(size, prob, rng));
                             ^
TypeError: sequence(...).map is not a function
```

**Comment by jacobbogers** [comment]
Thanks, I will take a look!

**Comment by jacobbogers** [comment]
Hi,
the n=1  returns a scalar, this was based on my wrong understanding of R in edge cases were n=1 or n=0.   aka `runinf(0)` or `runif(1)` for example, I thought they returned scalars but they were arrays

For now you can use  `c` to always make it an array  `c(sequece(1)).map(..` as a workaround

The new version will  seperate out the pure math functions and helper functions. the work is already done for all functions, but i need to update the docs)

**Comment by bluelovers** [comment]
@jacobbogers thx  for reply, but `libRmath.Multinomial(rng).rmultinom`

what is `c` ?

**Comment by jacobbogers** [comment]
`c` is an R function that is ported to javascript aswell  https://github.com/R-js/libRmath.js#flatten-or-c-alias
R counterpart https://www.rdocumentation.org/packages/base/versions/3.5.1/topics/c

**Comment by jacobbogers** [comment]
So
 ` c( sequence(1) ) <- an array `
 ` c(1,2,3) <- an array`
` c(1,2, c(4,5)) <- an array [1,2,4,5]`

**Comment by bluelovers** [comment]
another issues in npm v1.0.83

```ts
lib-r-math.js\dist\lib\webpack:\src\lib\multinom\rmultinom.ts:31
  const result = sequence(n).map(() => _rmultinom(size, prob, rng));
                             ^
TypeError: sequence(...).map is not a function
```

but in https://github.com/R-js/libRmath.js/blob/f775ba8899ca7538c45c734e03ce59c62771f718/src/lib/multinom/rmultinom.ts#L30-L37

is use randomGenHelper, but i see blame show it change at 2 month ago
does this also not yet push to npm too?

```ts
export function rmultinom(
  n: number,
  size: number,
  prob: number | number[],
  rng: IRNG
): number[] {
  return randomGenHelper(n, rmultinomOne, size, prob, rng)
}
```

**Comment by jacobbogers** [comment]
Hi Bluelovers
Thank you for your interest, awesome

btw: Did the 'c' function work for you?

Yes, the source code on git is already adjusted for the new situation, but documentation not adjusted yet)) There are some breaking changes, but needs  be crearly documented.  I need to swing around from my other projects to do this,

Pull request welcome)))

**Comment by bluelovers** [comment]
@jacobbogers 

im use `libRmath.Multinomial(rng).rmultinom` in current lib version at npm

there is no way import `_rmultinom` and re-pack to `c(sequece(n)).map(() => _rmultinom(size, prob, rng))`

so i can't use `c` for `rmultinom`

i think pr is no need, ur source code is use `randomGenHelper`, but just not yet publish to npm

**Comment by jacobbogers** [comment]
Ah i understand what you are trying to do i think,  you can wrap things is `c` it will stay forward compatible.

This should work
`c( sequece(n) ).map(() => c( rmultinom(size, prob, rng) ) )`

If you want, you can  post your code to jsfiddle, and I can take a look

**Comment by bluelovers** [comment]
demo code about what i saying lol

```ts
import libRmath = require('lib-r-math.js');

let rmultinomFn = libRmath.Multinomial(fakeLibRmathRng(Math.random)).rmultinom;

/**
 * n can't be 1 at current lib-r-math.js version (publish in npm)
 * 
 * and source code already change at github,
 * but not yet publish to npm
 */
let n = 1
let size = 21;

let ret = rmultinomFn(n, size, [1, 2]) // here will throw

console.log(ret);

export function fakeLibRmathRng(fn: () => number)
{
	return {
		unif_rand(n?: number)
		{
			if (n > 1)
			{
				let a = [];
				while (n--)
				{
					a[n] = fn()
				}
				return a;
			}

			return fn()
		},
	} as libRmath.IRNG
}

```

**Comment by jacobbogers** [comment]
hi, 
This is most certainly a bug!, the current npm version needs to be patched and released

thanks for finding it
```
const libR = require('lib-r-math.js')

const { rmultinom } = libR.Multinomial(); // use default PRNG

const relativeProbabilityWeights = [167, 500, 167, 167]

const data = rmultinom(1, 21, relativeProbabilityWeights); --> error
```

**Comment by jacobbogers** [comment]
can  you re-open this issue?) thanks (you have closed it)

**Comment by bluelovers** [comment]
I thought u are already fix it, just waiting some other job done, so didn't publish lol

**Comment by jacobbogers** [comment]
done, npm is now at version 1.0.85, the branch is lts-libr-v1, can you test?

Thanks again for finding the issue)

**Comment by bluelovers** [comment]
@jacobbogers it work without throw now

**Comment by jacobbogers** [comment]
ok, i will close the issue) thanks for finding it
