### ISSUE TITLE
how to do update this code to v2 ? Multinomial(rng)

### ISSUE THREAD

**Issue by bluelovers** [R-js/libRmath.js#188]
```ts
/**
	 * make rmultinom use with random.next
	 */
	const rmultinomFn = Multinomial(fakeLibRMathRng(() => random.next())).rmultinom;
```

**Comment by jacobbogers** [comment]
Hi @bluelovers 
That isolated piece of code is not meaningfull in any way. can you provide full isolated working example with version 1.x?

The Readme on [rmultinom][link]  contains both a full  isolated example in R and its equivalent in Typescript/Javascript

[link]: https://github.com/R-js/libRmath.js#the-multinomial-distribution

**Comment by jacobbogers** [comment]
sorry, not actionable, hence closed
