### ISSUE TITLE
Cannot find module in new installation

### ISSUE THREAD

**Issue by alejandrombc** [R-js/libRmath.js#21]
Hi all, I installed the libR package using 'npm install', but when I try to launch my application it gets an error message telling that it 'Cannot find module', this happends for a lot of functions in the package.

Example output:
`[ng] ERROR in node_modules/lib-r-math.js/dist/src/lib/beta/index.d.ts(4,27): error TS2307: Cannot find module '../types'.
[ng] node_modules/lib-r-math.js/dist/src/lib/binomial-negative/index.d.ts(3,25): error TS2307: Cannot find module 'src/lib/types'.
[ng] node_modules/lib-r-math.js/dist/src/lib/binomial-negative/index.d.ts(3,148): error TS2307: Cannot find module 'src/lib/types'.
[ng] node_modules/lib-r-math.js/dist/src/lib/binomial-negative/index.d.ts(4,25): error TS2307: Cannot find module 'src/lib/types'.
[ng] node_modules/lib-r-math.js/dist/src/lib/binomial-negative/index.d.ts(4,166): error TS2307: Cannot find module 'src/lib/types'.
[ng] node_modules/lib-r-math.js/dist/src/lib/binomial-negative/index.d.ts(5,25): error TS2307: Cannot find module 'src/lib/types'.
[ng] node_modules/lib-r-math.js/dist/src/lib/binomial-negative/index.d.ts(5,166): error TS2307: Cannot find module 'src/lib/types'.
[ng] node_modules/lib-r-math.js/dist/src/lib/binomial-negative/index.d.ts(6,102): error TS2307: Cannot find module 'src/lib/types'.`

Is this normal?.

Thanks in advance

**Comment by jacobbogers** [comment]
Hi alejandrombc,
thanks for filing an issue,
It seems like it cannot find typescript definitions, let me look into this.
Just in case can you share your code snippet
thank you!

**Comment by alejandrombc** [comment]
Hi!, I'm just importing the Normal function, like this:

`import { Normal } from 'lib-r-math.js';`

But I'm willing to use the qnorm function in it, like this: 
`const { rnorm, pnorm, qnorm } = Normal();`

Thanks for your time!

I'm using Angular 7 with Ionic 4 (if that helps)

**Comment by jacobbogers** [comment]
Hi,
I replicated your samples (within ts-node)
This works for me
```javascript
import { Normal } from 'lib-r-math.js';
const { rnorm, pnorm, qnorm } = Normal();
rnorm(10);
/* ->
[ 1.2629542848807933,
  -0.3262333607056494,
  1.3297992629225006,
  1.2724293214294047,
  0.4146414344564082,
  -1.5399500419037095,
  -0.9285670347135381,
  -0.2947204467905602,
  -0.005767172747536955,
  2.404653388857951 ]
*/
```
Is this an issue with your IDE? (cant find typedefs) or during transpilation webpack?.
Could you share a sample github repo that replicates this issue? thanks

**Comment by jacobbogers** [comment]
Hi @alejandrombc 
I made a minimal working example unsing `libRmathjs`  using typescript+webpack, targetting a browser,
It is a new repo for R-js, that will contain all examples and tutorials, I added a use case for this issue as a first
https://github.com/R-js/examples
Let me know if this example fits your usecase.
