### ISSUE TITLE
Question - moment generating functions

### ISSUE THREAD

**Issue by moob123** [R-js/libRmath.js#22]
Hello,
First of all, I am greatful for the effort.
A question: are you planning to implement the moment ganerating functions? (or have I overlooked it?)

**Comment by jacobbogers** [comment]
Hi,
Thank you,
`libRmath` is port of all the functions in  R "nmath" core , i am now doing all functions in `r-stat` package, there are over 1300 of them. 

Moment generating functions are not part of R "nmath" core, of course R ecosystem consist of many packages and has more then one that calculate `moments` and `cummulants`

https://cran.r-project.org/web/packages/moments/index.html

### Solutions:

- using the existing functions `rexp`. you can calculate [moments](https://bookdown.org/probability/beta/moment-generating-functions.html) with minimal code.

- port the R "moments" package.

I will put the "moments" package on my todo list in any case.

**Comment by jacobbogers** [comment]
Addition, I actually prefer this package more [gemm](https://cran.r-project.org/web/packages/gmm/index.html)

The problem is there are more then one package in the R ecosystem calculating moments, hard to choose.

What package has your preference?

**Comment by moob123** [comment]
Hello, I have an interest in integrating stat functions into our JS based solution - and think R is a good reference point -  I am not coming from the R community.

**Comment by moob123** [comment]
Hello, maybe not a topic in issues, but is there a commercial license you provide if we bundle your package into a commercial solution ? thanks.

**Comment by jacobbogers** [comment]
Thanks for your interest, I have received your email and will reply to you shortly via email
