### ISSUE TITLE
summary got error with large array

### ISSUE THREAD

**Issue by iwater** [R-js/libRmath.js#24]
when array size greater than 130000

summary got error as below
UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded

**Comment by jacobbogers** [comment]
Hi, do you have a code sample to reproduce the problem? what command did you execute? Note: 130'000 sounds like alot, you did it in browser or in nodejs?
Thanks

**Comment by iwater** [comment]
just in nodejs v11.10.0

sample.log

0.007 1547484806.852 /api/v0.19/ads
0.044 1547484806.896 /api/v0.19/log
0.049 1547484806.901 /api/v0.19/customer-events/events?page=1&limit=5
0.051 1547484806.903 /api/v0.19/customer-events/events?page=1&limit=20
0.134 1547484806.986 /api/v0.19/ads
0.137 1547484806.989 /api/v0.19/ads


const fs = require('fs');
const readline = require('readline');
const libR = require('lib-r-math.js');
const { summary } = libR.R;

const numbers = []

async function processLineByLine() {
  const fileStream = fs.createReadStream('sample.log');

  const rl = readline.createInterface({
    input: fileStream,
    crlfDelay: Infinity
  });

  for await (const line of rl) {
    const parts = line.split(' ')
    const time = +parts[0]
    numbers.push(time)
  }
}

processLineByLine().then(() => {
  console.log(summary(numbers.slice(0, 130000)))
})

**Comment by jacobbogers** [comment]
Thanks for your example,

Yes this method can be made more memory efficient to handle superlarge datasets
Will fix it today and release new version.

I will notify you when it is done

**Comment by jacobbogers** [comment]
I fixed it in the `lts` branch, need to do some testing (large dataset) to see if it works,

**Comment by jacobbogers** [comment]
### version is now 1.0.86

Hi,
the new release was tested with 50 million numbers,  note at 100 million, nodejs itself gets memory errors, so that has nothing to do with my library
```
const libR = require('lib-r-math.js');
const { summary } = libR.R;

const length = 5E7; // 50 million

const numbers = Array.from({length}, () => Math.random()*2-1); // random numbers between -1 and 1

//mean => 0
//theoretical variance => 1/3 = 0.33333
//theoretical standard deviation => 1/sqrt(3) = 0.57735

console.log(summary(numbers))
/* output 

**{ 
  N: 50000000,
  mu: -0.000006798457015052945,
  population: { variance: 0.3333594618593985, sd: 0.5773728967135524 },
  sample: { variance: 0.3333594685265879, sd: 0.5773729024872815 },
  relX: 'depricated',
  relX2: 'depricated',
  stats:
   { min: -0.999999968540858,
     '1st Qu.': -0.4999896768701041,
     median: -0.00005591832876761238,
     '3rd Qu.': 0.5000730743743234,
     max: 0.9999999895607647 } }
**/
```

**Comment by jacobbogers** [comment]
let me know if it works for you, so i can close the ticket

**Comment by iwater** [comment]
OK, I will test it, thanks

**Comment by iwater** [comment]
in my case, there are 200 million numbers, and that works now with new version

**Comment by jacobbogers** [comment]
Fantastic, i will close the ticket, thanks for contribution.
