### ISSUE TITLE
Build Failures

### ISSUE THREAD

**Issue by matt4530** [R-js/libRmath.js#25]
Some issues I found after building from source:

1. There is a missing `devDependency` to `clean-webpack-plugin@1.0.1`. (it doesn't work with v2)
2. There are a few linting errors which cause `build` and `build:prod` to fail. 

I've fixed these build issues in this commit on a fork I made if anyone is having this same problem: https://github.com/UnknownGuardian/libRmath.js/commit/91450a6eac64d2691cd82b2b5ff169a57f654923

Another issue is that the dependency on `istanbul` could be updated to fix some security vulnerabilities with its dependencies.

**Comment by jacobbogers** [comment]
Thanks for fixing the dependencies, they are a bit dated indeed, if you can put your changes into a PR i would greatly appreciate it

**Comment by jacobbogers** [comment]
The git branch that is sync with npm is name **lts-libr-v1s**
I have changed this to the default branch the corresponding README.md file will reflect the correct description of the currently released code in npm
