### ISSUE TITLE
TS Documentation is out of date for NPM version

### ISSUE THREAD

**Issue by matt4530** [R-js/libRmath.js#26]
There are quite a few versions listed on NPM.
https://www.npmjs.com/package/lib-r-math.js?activeTab=versions

Unfortunately, these versions don't correspond to a release or tag on Github, so we have to match by date if we want a previous version.

It appears that the current version on NPM doesn't follow the examples listed in code.

For example, 
1. distribution functions no longer take in a type `numVector` (a number or scalar) but instead are only `number`. The documentation shows that the vector format is still valid. 
2. There is no import called `R`. It seems to have been renamed `utils` and has only some methods available.

For those interested in using the same version that is used in the documentation, you can just `npm install lib-r-math.js@1.0.83`. This version is just 2 behind the current NPM version.

**Comment by jacobbogers** [comment]
(edited)
I apologize, the lts version was not correctly tagged as "@latest"
I will correct for it, to bring the "npm" module release in line with the documentation

**Comment by jacobbogers** [comment]
The git branch that is sync with npm is name **lts-libr-v1s**
I have changed this to the default branch the corresponding README.md file will reflect the correct description of the currently released code in npm
