### ISSUE TITLE
incorrect value and long running time in pnt/qnt

### ISSUE THREAD

**Issue by richarddmorey** [R-js/libRmath.js#39]
Consider the following R code:

```
qt(0.025, 1544, -1.96596032513375, FALSE)
# [1] -0.0059973

pt(-0.00599730016852873, 1544, -1.96596032513375, FALSE)
# [1] 0.025
```

When I run the following javascript code:

```

const {
  StudentT,
} = require('lib-r-math.js');
 
const { pt, qt }  = StudentT();

var before, after, x, p;

before = new Date;
x = qt(0.025, 1544, -1.96596032513375, false)
after = new Date;

console.log(`Value: ${x}; time: ${(after - before)/1000}s`);

before = new Date;
p = pt(-0.00599730016852873, 1544, -1.96596032513375, false)
after = new Date;

console.log(`Value: ${p}; time: ${(after - before)/1000}s`);
```

I get the output:
```
Value: -6.177909933079164e-161; time: 11.518s
Value: 0.028760991032743953; time: 0.03s
```

That is, the returned values are incorrect and it takes over 11 seconds to run (!). There's definitely something wrong somewhere. Given that the value of `pnt` seems to be wrong (about .029 instead of .025) I'm guessing there's a problem in `pnt` that causes the inversion of `pnt` that `qnt` uses to fail.

Edit: I should add that I'm using 1.0.86 as published here: https://www.npmjs.com/package/lib-r-math.js

**Comment by richarddmorey** [comment]
Exploring the issue further, there definitely seems to be an issue in `pnt`. I've compared the values with R using the following code:

```
library(dplyr)
library(ggplot2)
library(patchwork)
library(glue)

ncp = 3

## This code assumes the the javascript can be
## run from the current working directory
js = glue::glue(
"const {{
  StudentT,
}} = require('lib-r-math.js');
 
const {{ pt, qt }}  = StudentT();

var x, p;
var df = 1544;
var ncp = {ncp};

for(let x=-5;x<=5;x+=.01)
    console.log(`${{x}} ${{df}} ${{ncp}} ${{pt(x, df, ncp)}}`)
")

js_fn = "tmp.js"
out_fn = "test.txt"

cat(js, file = js_fn)

system(glue::glue("node {js_fn} > {out_fn}"))


read.table('test.txt',
           col.names = c("x","df","ncp","pt")) %>%
  mutate(pt_r = pt(x,df,ncp),
         err = pt - pt_r,
         rel_err = 100*err/pt_r) -> z
z %>%
  ggplot(aes(x=pt_r,y=rel_err)) +
  geom_point() + 
  scale_x_continuous(name = "pt (R)", trans="log") +
  scale_y_continuous(name = "% rel. error, lib-r-math.js vs R") +
  geom_vline(xintercept = pnorm(-z$ncp[1])) +
  geom_hline(yintercept=0,col="red") -> p1

z %>%
  ggplot(aes(x=pt_r,y=pt)) +
  geom_point() + 
  scale_x_continuous(name = "pt (R)", trans="log") +
  scale_y_continuous(name = "pt (lib-r-math.js)", trans="log") +
  geom_vline(xintercept = pnorm(-z$ncp[1])) +
  geom_abline(slope=1,intercept=0, col = "red") -> p2


print(p1 / p2)
```

which produces the following graph:
![lib-R-math](https://user-images.githubusercontent.com/1284826/93718669-9b17e000-fb75-11ea-8c9c-ea6021c64a42.png)

The accuracy of the computation is very poor for small values of x for even a moderate noncentrality parameter like 3. There is also a major discontinuity in the computation at x=0.

I think what might be going on with `qnt` is that the inversion fails due to the poor accuracy of `pnt` around the discontinuity: the loop in the inversion has a difficult time achieving the desired accuracy, hence the long computation times.

**Comment by richarddmorey** [comment]
The problem appears to be in `Toms708.bratio` (the incomplete beta function). The R source code has this (`toms708.c`, line [186](https://github.com/wch/r-source/blob/761af23c85f6d0062a88fe86fdaa269c82591ce8/src/nmath/toms708.c#L186)):

```
do_swap = (x > 0.5);
	if (do_swap) {
	    SET_0_swap;
	} else {
	    SET_0_noswap;
	}
```

whereas the `toms708.ts` (line [1646](https://github.com/R-js/libRmath.js/blob/306df9aa9a17c323a0dfd7418a4c859270606f7c/src/lib/common/toms708/toms708.ts#L1646)) has this:

```
 if (x <= 0.5) {
        ind = 1;
        a0 = b;
        b0 = a;
        x0 = y;
        y0 = x;
      }
```

Notice the inequalities are opposite. When I correct the inequality to `>` instead of `<=`, I get the same value as R in `bratio`. Of course, `pnt` calls `pbeta` which calls `bratio`, so fixing this should (?) fix the problem.

**Comment by richarddmorey** [comment]
Ah, so, the pull request does indeed fix the problem with the discontinuity at 0 and the original inaccuracy and slowdown, but there are still strange discontinuities near t = -1 and t = 1. Overall, the function works much better with the pull request but it is still wrong.

You can see the problem by computing in R:

```
pt(-.9, 1544, 3)
# [1] 4.822699e-05
pt(-.99, 1544, 3)
# [1] 3.314727e-05
pt(-.999, 1544, 3)
# [1] 3.1914e-05
```

and using the `lib-r-math` code after my pull request:

```
console.log(pt(-.9, 1544, 3));
// 0.00004822733930143208
console.log(pt(-.99, 1544, 3));
0.00003314900229733908
//console.log(pt(-.999, 1544, 3));
0

```

Likewise near t = 1, for R:

```
pt(.9, 1544, 3)
# [1] 0.01787012
pt(.99, 1544, 3)
# [1] 0.02222399
pt(.999, 1544, 3)
# [1] 0.0227049
```

and `lib-r-math`:

```
console.log(pt(.9, 1544, 3));
// 0.01787012439806198
console.log(pt(.99, 1544, 3));
// 0.02222398920953306
console.log(pt(.999, 1544, 3));
// 0.03281844539269633
```

I'll try to get to the bottom of these, but maybe hold off on the pull request.

**Comment by jacobbogers** [comment]
Most Outstanding Richard,!!

**Comment by jacobbogers** [comment]
I will distribute new version this weekend on npm, (been busy with some job-chores so far) thanks again.

**Comment by richarddmorey** [comment]
Great, thanks. I'll close this up.

**Comment by jacobbogers** [comment]
version 1.0.88 released with your changes,
