### ISSUE TITLE
"Uncaught ReferenceError: require is not defined"

### ISSUE THREAD

**Issue by chrispsn** [R-js/libRmath.js#4]
Hi, trying to use this in a web context. I believe I followed your instructions (and also `build:prod`-ed the files using yarn) but keep getting the error in the title. Am I looking in the wrong directory?

Also - perhaps a typo (`.`) in your readme?:

```
const libR = window.libR.;
```

**Comment by jacobbogers** [comment]
#### for the first part:

could you provide how you require/import the lib? 
if you use  with `require` / `import`  then you need a bundler (webpack, gulp)  if your target is web 

#### on the second part:

 , yes that is most certainly a typo!

The `<script`  tag example is only if you use the file from './dist' in a CDN like fashion.

Good find! I corrected!

**Comment by chrispsn** [comment]
Thanks. For #1, I'm trying to use the instructions in your readme under Installation -> Web. Is there a pre-built version that I can use via a 'script' tag directly? Building one myself via 'build:prod' leads to the error in the title.

**Comment by chrispsn** [comment]
Put another way: how do I access the file at './dist'? Is it provided with the project already? I can't see it in the directory tree.

**Comment by jacobbogers** [comment]
Hi,
I found the issue, your finding is correct,
somehow I forgot to whitelist 2 dependencies, ("debug" and "ms").

They are now included into the bundle during builds.

I published a new version on npm, You can do  `npm upgrade`  to fetch the new version with the fix, 

If you are using git repo to build yourself, you need to do `git pull`

**Comment by chrispsn** [comment]
Thanks very much! Works great.

FYI - playing around with it here. https://twitter.com/mesh_ide/status/976438099780583425

**Comment by ds604** [comment]
I received the same error (Uncaught ReferenceError: require is not defined) trying to run the "web" example as presented on the home page (using version 1.0.74). Changing the version number to 1.0.86 fixes the issue:

```html
<script src="https://unpkg.com/lib-r-math.js@1.0.86/dist/lib/libR.min.js"></script>
<script>
  const libR = window.libR;
  //fetch some distribution namespaces
  const { Tukey, Normal, Beta, StudentT, Wilcoxon } = libR;
  const { sum } = libR.R

  console.log(sum([1,2,3,4]))
</script>
```

Nice project!

**Comment by jacobbogers** [comment]
Thanks,  working in the webassembly version... stay tuned

**Comment by ds604** [comment]
Do you mind my asking, is the Webassembly version still written in Typescript (maybe using Assemblyscript), or did the change necessitate a change in language? I've been trying to keep current on some of these developments in how scientific computing is being migrated to the web.

**Comment by jacobbogers** [comment]
Hi, sorry for the late reply, lots of irons in the fire,
No its human readable "wat" format, its not Assemblyscript, I was actually going to use GPU,but I need to wait for the "compute shader" to become available in early 2020, (chrome beta (canary) has it now as alpha). Will keep you updated

**Comment by weisserw** [comment]
As of this writing, the example in the README still uses 1.0.74 and throws this error.

**Comment by jacobbogers** [comment]
@weisserw 
Hi,
Thanks, the version is 1.0.89 , I will update the doc
Meanwhile here is a jsfiddle link that shows how to use rnorm(4) 
https://jsfiddle.net/jacobot/L3vpy410/

```html
<script src="https://unpkg.com/lib-r-math.js@1.0.89/dist/lib/libR.min.js"></script>
```
```javascript
const libR = window.libR;
  //fetch some distribution namespaces
const { Tukey, Normal, Beta, StudentT, Wilcoxon } = libR;

const norm = new Normal();

console.log(norm.rnorm(4))
```

**Comment by jacobbogers** [comment]
> As of this writing, the example in the README still uses 1.0.74 and throws this error.

Updated the README.md, also example has more meat to the done))
https://github.com/R-js/libRmath.js/pull/73

**Comment by MaxGraey** [comment]
Btw about WebAassembly and AssemblyScript I recently start to implement a simple and minimalistic library exclusively for generating and analyzing probability distributions: https://github.com/MaxGraey/as-random
The main goal is to achieve speed and simplicity, neglecting accuracy in some places.
