### ISSUE TITLE
Building fails due to case sensitivity of filename

### ISSUE THREAD

**Issue by sdwfrost** [R-js/libRmath.js#5]
The following build script fails:

```sh
npm run-script build
```

due to [this line](https://github.com/jacobbogers/libRmath.js/blob/master/src/lib/exp/rexp.ts#L38)

```js
import { IRNG } from '../rng/IRNG';
```

which should read

```js
import { IRNG } from '../rng/irng';
```

**Comment by jacobbogers** [comment]
Hi , 

Although NTFS claims to be case sensitive, it doesn't appear to be that case,

Thanks for finding the issue, It has been corrected, you can either `git pull`  or  `npm upgrade`
