### ISSUE TITLE
Usage with Typescript

### ISSUE THREAD

**Issue by ellis** [R-js/libRmath.js#6]
Could you please show an example of how to use the library in a typescript project?  When installed from npm, it appears that the typescript declarations are missing?

**Comment by jacobbogers** [comment]
Good find, I see not all types are generated (only some)
types d.ts files are in the directory pointed to by `types` field in package.json. of the module..
Looking into it

**Comment by jacobbogers** [comment]
Hi, I have all d.ts files exported (version 1.0.81)
Here is an example (I use vscode and see "hints" when typing).
```
import { R, rng, Normal, IRNG, IRNGNormal } from 'lib-r-math.js';

const { SuperDuper, normal: { BoxMuller } } = rng;
const { asArray } = R;

const rngUnif: IRNG = new SuperDuper(123);
const rngNorm: IRNGNormal = new BoxMuller(rngUnif);

const { rnorm, pnorm, qnorm } = Normal(new BoxMuller(new SuperDuper(123)));

const data = rnorm(15);
```

**Comment by ellis** [comment]
Awesome, works great!
