### ISSUE TITLE
Typescript types are not exported

### ISSUE THREAD

**Issue by MelleB** [R-js/libRmath.js#67]
Hi,

I cannot seem to find the types of the package, although the README mentions they should be exported.
Looking in my `node_modules/lib-r-math.js` folder, there is a single typescript file called `dist/src/lib/r-func.d.ts` file, which does not have all the type declarations.

The file that is mentioned in `package.json` is `dist/src/lib/index.d.ts`, this file does not seem to exist.
I've installed version `1.0.88`

Would this be an easy fix?

Thanks!

**Comment by jacobbogers** [comment]
Thanks for discovering the issue, will make a new release with the type def files
(edit: my bad, seems I didn't generate all of the typedef files for version x.88 , they are there for version x.86) will correct asap and release new version.

**Comment by jacobbogers** [comment]
@MelleB 
I have fixed the issue , decleration files are now part of the package, the version has been bumped to 1.0.89
Thanks for catching the issue

**Comment by jacobbogers** [comment]
fixed in release  1.0.89 please update

**Comment by jacobbogers** [comment]
fixed , new version is now 1.0.89
